# Default values for web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

webserver:
  name: webserver

  image:
    name: IMAGE_NAME
    tag: latest
    exposedPort: 80
    pullPolicy: Always

  replicaCount: 1

  service:
    type: NodePort
    nodePort: 30001
