apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.webserver.name }}-deployment

spec:
  replicas: {{ .Values.webserver.replicaCount }}

  selector:
    matchLabels:
      server: {{ .Values.webserver.name }}

  template:
    metadata:
      labels:
        server: {{ .Values.webserver.name }}
    spec:
      containers:
        - name: {{ .Values.webserver.name }}
          image: {{ .Values.webserver.image.name }}:{{ .Values.webserver.image.tag }}
          imagePullPolicy: {{ .Values.webserver.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webserver.image.exposedPort }}
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
