---
- name: Test communication with K3s nodes
  hosts: k3s
  tasks:
    - name: Ping all EC2
      ansible.builtin.ping:

- name: Install K3s on Server
  hosts: k3s-server
  become: true
  tasks:
    - name: Copy K3s config file
      ansible.builtin.copy:
        src: server.config.yaml
        dest: /etc/rancher/k3s/config.yaml
        owner: root
        group: root
        mode: 0644

    - name: Install K3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -s -

- name: Install K3s on Agent
  hosts: k3s-agent
  become: true
  tasks:
    - name: Copy K3s config file
      ansible.builtin.copy:
        src: agent.config.yaml
        dest: /etc/rancher/k3s/config.yaml
        owner: root
        group: root
        mode: 0644

    - name: Install K3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC=agent sh -s -
