name: Create dev cluster with Terraform and install K3s with Ansible

on:
  workflow_dispatch:
  # push:
  #   branches: ['main']

env:
  AWS_REGION: us-east-1

# Enable OpenID Connect for AWS
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  create-cluster-terraform:
    name: Create cluster with Terrafrom
    runs-on: ubuntu-latest

    # Set the default shell and working-directory to all run steps in the job
    defaults:
      run:
        shell: bash
        working-directory: ./environments/dev

    steps:
      # Configure AWS credentials and region environment variables
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE}}
          aws-region: ${{ env.AWS_REGION }}

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout source code
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init -backend-config=backend.conf

      # Build or apply changes to infrastructure according to Terraform configuration files
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      # Export workflow artifacts
      - name: Export SSH private key artifact
        uses: actions/upload-artifact@v4
        with:
          name: k3s-key.pem
          path: ./environments/dev/ansible/k3s-key.pem

      - name: Upload artifacts for Ansible
        uses: actions/upload-artifact@v4
        with:
          name: ansible-artifacts
          path: |
            ./environments/dev/ansible/k3s-key.pem
            ./environments/dev/ansible/inventory.ini
            ./environments/dev/ansible/server.config.yaml
            ./environments/dev/ansible/agent.config.yaml

  install-k3s-ansible:
    name: Install K3s with Ansible
    runs-on: ubuntu-latest

    # Set the default shell and working-directory to all run steps in the job
    defaults:
      run:
        shell: bash
        working-directory: ./environments/dev/ansible

    steps:
      # Configure AWS credentials and region environment variables
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE}}
          aws-region: ${{ env.AWS_REGION }}

      # Wait for EC2 creation and validate instance status check
      - name: Wait for Infrastructure Creation by Terraform
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=nioyatech-k3s*" "Name=instance-state-name,Values=running" \
            --query 'Reservations[*].Instances[*].InstanceId' \
            --region us-east-1 --output text | sed 's/\t/,/g')
          echo "List of running instances with 'nioyatech-k3s*' tag (if any):"
          echo "$INSTANCE_IDS"
          aws ec2 wait instance-status-ok --instance-ids $INSTANCE_IDS --region us-east-1

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout source code
        uses: actions/checkout@v4

      # Downdload artifacts for Ansible created in previous job
      - name: Downdload artifacts
        uses: actions/download-artifact@v4
        with:
          name: ansible-artifacts # Name of the artifact to download
          path: ./environments/dev/ansible/ # Destination path

      # Install K3s with Ansible
      - name: Install K3s with Ansible
        run: |
          ls -al
          ansible --version
          ansible-playbook ./playbook.yaml
