    region         = "us-east-1"
    bucket         = "remote-state-s3-nioyatech"
    key            = "dev/terraform.tfstate"
    encrypt        = true
    dynamodb_table = "remote-state-dynamodb-nioyatech"
